Set bgp keepalive_interval to it's default 20
terraform-google-modules/terraform-google-vault pull request #169
Opened 2023-02-13 10:47 UTC by dlouvier

`keepalive_interval` is not set and this value needs to be between 20 and 60.

> If set, this value must be between 20 and 60. The default is 20.

[Provider documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router#keepalive_interval)

As this is not set, every time we run `terraform plan`, the plan outputs this change and it is quite noisy.

![image](https://user-images.githubusercontent.com/13359249/218437795-62544c00-7381-4bf0-a5d1-940e18d26828.png)

2023-02-14 10:00 UTC, dlouvier commented
Hello @cft-admins could you run /gcbrun ?

Thanks

2023-02-16 20:28 UTC, apeabody requested changes
Thanks for the contribution @dlouvier! - Can you PTAL?

2023-02-16 20:28 UTC, apeabody commented on network.tf
> +    bgp = 20
Should this be `keepalive_interval`?

```suggestion
    keepalive_interval = 20
```

2023-02-16 20:28 UTC, apeabody commented
/gcbrun

2023-02-16 20:33 UTC, apeabody commented
Looks like `keepalive_interval` was added in TPG 4.53.0, would need to also bump https://github.com/terraform-google-modules/terraform-google-vault/blob/master/versions.tf#L23

2023-02-16 20:42 UTC, apeabody commented
Thanks @dlouvier! - Some relevant output from the LINT tests:

```
terraform_validate . 
╷
│ Error: Unsupported argument
│ 
│   on network.tf line 56, in resource "google_compute_router" "vault-router":
│   56:     bgp = 20
│ 
│ An argument named "bgp" is not expected here.
╵
terraform_validate ./examples/shared_vpc_internal 
Success! The configuration is valid.

terraform_validate ./examples/vault-on-gce 
╷
│ Error: Unsupported argument
│ 
│   on ../../network.tf line 56, in resource "google_compute_router" "vault-router":
│   56:     bgp = 20
│ 
│ An argument named "bgp" is not expected here.
╵
terraform_validate ./modules/cluster 
Success! The configuration is valid.

terraform_validate ./test/fixtures/simple_external 
╷
│ Error: Unsupported argument
│ 
│   on ../../../network.tf line 56, in resource "google_compute_router" "vault-router":
│   56:     bgp = 20
│ 
│ An argument named "bgp" is not expected here.
╵
terraform_validate ./test/setup 
```

2023-02-17 09:32 UTC, dlouvier commented
Sure, thanks for your fix @apeabody

2023-02-17 13:58 UTC, apeabody commented
/gcbrun

2023-02-21 22:19 UTC, apeabody commented
Hi @dlouvier - Looks like just needs a `terraform fmt`:

```
Running terraform fmt
network.tf
--- old/network.tf
+++ new/network.tf
@@ -52,7 +52,7 @@
   network = local.network
 
   bgp {
-    asn = 64514
+    asn                = 64514
     keepalive_interval = 20
   }
 
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
```

2023-03-02 16:30 UTC, dlouvier commented on network.tf
>      asn = 64514
```suggestion
    asn                = 64514
```

2023-03-02 16:32 UTC, dlouvier commented
/gcbrun

2023-03-02 16:33 UTC, dlouvier commented
@apeabody hey sorry, I did abandoned this. Fixed the format (I was editing from the GitHub UI and yep... it seemed straight forward but it wasn't).

Can you run tests again ? Should be good now.

2023-03-02 17:41 UTC, dlouvier commented
🚀

2023-03-03 00:16 UTC, apeabody reviewed
Thanks for the contribution @dlouvier!

@bharathkkb - This might cause "churn" during first application, but as it's already a breaking change for TPG I think that should be OK?

2023-03-07 16:04 UTC, dlouvier commented
Any update folks,

@apeabody @bharathkkb 
Can you run again `/gcbrun` ? 

I've rebased the PR as there was a commit in the main branch.

2023-03-07 16:05 UTC, apeabody commented
/gcbrun

2023-03-07 18:33 UTC, apeabody approved these changes
Thanks for the contribution @dlouvier!

2023-03-07 18:33 UTC, merged

2023-03-08 10:09 UTC, dlouvier commented
you welcome, see ya around!